version: "3.8"

services:
  backend:
    image: harshjadhav003/docker-setup-backend:latest
    ports:
      - "3002:3002"
    restart: always

  frontend:
    image: harshjadhav003/docker-setup-frontend:latest
    ports:
      - "5173:80"
    restart: always

  dashboard:
    image: harshjadhav003/docker-setup-dashboard:latest
    ports:
      - "5174:80"
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always