services:
  backend:
    build:
      context: ../backend
    ports:
      - "3002:3002"
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  dashboard:
    build:
      context: ../dashboard
    ports:
      - "5174:5173"
    volumes:
      - ../dashboard:/app
      - /app/node_modules
    depends_on:
      - backend